name: Collect Item Info
on:
  repository_dispatch:
    types: [info]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run binary
        run: ./bin/info
        env:
          DB_URL: ${{ secrets.DB_URL }}
