name: Creation Chain
run-name: Creation Chain

on:
  repository_dispatch:
    types: ["pipeline"]
  schedule:
    - cron: "0 12 * * *"

jobs:
  queries:
    uses: ./.github/workflows/queries.yaml
    with:
      run: false
    secrets: inherit

  runners:
    needs: queries
    uses: ./.github/workflows/runners.yaml
    secrets: inherit
