name: Application One
run-name: SDLC for Application One 🚀

on:
  repository_dispatch:
    types: ["pipeline"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run composite action
        uses: ./.github/workflows/queries.yaml

  queries:
    needs: build
    uses: ./.github/workflows/queries.yaml
    secrets: inherit

  assign:
    needs: queries
    uses: ./.github/workflows/assign.yaml
    secrets: inherit
