name: Application One
run-name: SDLC for Application One 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.actor }} with ${{ github.event_name }} event, status is ${{ job.status }}."

  sast:
    needs: build
    uses: ./.github/workflows/assign.yaml
    secrets: inherit

  sast2:
    needs: sast
    uses: ./.github/workflows/queries.yaml
    secrets: inherit
