name: Create Chain

on:
  repository_dispatch:
    types: ["pipeline"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Queries
        uses: ./.github/workflows/queries.yaml

  queries:
    needs: build
    uses: ./.github/workflows/queries.yaml
    secrets: inherit

  assign:
    needs: queries
    uses: ./.github/workflows/assign.yaml
    secrets: inherit
