name: Application One
run-name: SDLC for Application One 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.actor }} with ${{ github.event_name }} event, status is ${{ job.status }}."
  sast:
    needs: build
    uses: ./.github/workflows/assign.yaml
    secrets:
      DB_URL: ${{ secrets.DB_URL }}
    vars:
      DB_NAME: ${{ vars.DB_NAME }}
      QUERY_DB_NAME: ${{ vars.QUERY_DB_NAME }}

  sast2:
    needs: sast
    uses: ./.github/workflows/queries.yaml
    with:
      run-name: "Static Application Security Testing for Application-One"
