name: Creation Chain
run-name: Creation Chain

on:
  repository_dispatch:
    types: ["pipeline"]

jobs:
  queries:
    uses: ./.github/workflows/queries.yaml
    secrets: inherit

  runners:
    needs: queries
    uses: ./.github/workflows/assign.yaml
    secrets: inherit

  runners2:
    needs: queries
    uses: ./.github/workflows/assign.yaml
    secrets: inherit

  run3:
    needs: runners2
    uses: ./.github/workflows/assign.yaml
    secrets: inherit
