name: Create Chain

on:
  repository_dispatch:
    types: ["pipeline"]

jobs:
  queries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run queries job
        uses: ./.github/workflows/queries.yaml

  runners:
    needs: queries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run runners job
        uses: ./.github/workflows/assign.yaml
