name: Create Chain

on:
  repository_dispatch:
    types: ["pipeline"]

jobs:
  queries:
    needs: build
    uses: ./.github/workflows/queries.yaml
    secrets: inherit

  runners:
    needs: queries 
    uses: ./.github/workflows/assign.yaml
    secrets: inherit
