name: Create Queries

on:
  repository_dispatch:
    types: ["queries"]

jobs:
  create-queries:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make binary executable
      run: chmod +x ./bin/queries

    - name: Run binary
      env:
        DB_URL: ${{ secrets.DB_URL }}
        DB_NAME: ${{ secrets.DB_NAME }}
        QUERY_DB_NAME: ${{ secrets.QUERY_DB_NAME }}
      run: ./bin/queries
