name: Create Queries
on:
  repository_dispatch:
    types: ["queries"]
  workflow_call:
    inputs:
      run:
        description: "Whether to run the job or not"
        required: false
        default: true

jobs:
  create:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make binary executable
        run: chmod +x ./bin/queries

      - name: Run binary
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_NAME: ${{ vars.DB_NAME }}
          QUERY_DB_NAME: ${{ vars.QUERY_DB_NAME }}
        run: ./bin/queries
