name: Create Queries

on:
  repository_dispatch:
    types: ["queries"]

jobs:
  create-queries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make binary executable
        run: chmod +x ./bin/queries

      - name: Run binary
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_NAME: ${{ vars.DB_NAME }}
          QUERY_DB_NAME: ${{ vars.QUERY_DB_NAME }}
        run: |
          output=$(./bin/queries)
          if [ -n "$output" ]; then
            echo "CHANGED=true" >> $GITHUB_ENV
            echo "$output"
          fi

      # - name: Check output and run subsequent steps
      #   if: ${{ env.CHANGED != '' }}
      #   env:
      #     DB_URL: ${{ secrets.DB_URL }}
      #     DB_NAME: ${{ vars.DB_NAME }}
      #     QUERY_DB_NAME: ${{ vars.QUERY_DB_NAME }}
      #   run: ./bin/assign
    second_workflow:
    uses: ./.github/workflows/assign.yaml
