name: Assign Runners
run-name: Assign Runners

on:
  repository_dispatch:
    types: ["assign"]
  workflow_call:
    inputs:
      run:
        description: "Whether to run the job or not"
        required: false
        default: true
        type: boolean

jobs:
  assign:
    runs-on: ubuntu-latest
    if: ${{ inputs.run == true }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make binary executable
        run: chmod +x ./bin/profit

      - name: Run binary
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_NAME: ${{ vars.DB_NAME }}
          QUERY_DB_NAME: ${{ vars.QUERY_DB_NAME }}
        run: ./bin/profit --assign-runners

  create:
    needs: assign
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Make binary executable
        run: chmod +x ./bin/profit

      - name: Run binary
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_NAME: ${{ vars.DB_NAME }}
          QUERY_DB_NAME: ${{ vars.QUERY_DB_NAME }}
        run: ./bin/profit --create-runners

      - name: Set up Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Check for changes
        id: check_changes
        run: |
          if ! git diff --quiet; then
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push changes
        if: env.CHANGED == 'true'
        run: |
          git add .
          git commit -m "add runners"
          git push
