name: runner_3
run-name: Runner 3
"on":
  repository_dispatch:
    types: [run0]
jobs:
  run_binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env: {}
      - name: Make binary executable
        run: chmod +x ./bin/profit
        env: {}
      - name: Run binary
        run: ./bin/profit --runner-id=3
        env:
          DB_URL: ${{ secrets.DB_URL }}
          AUTH_TOKEN: ${{ secrets.DB_AUTH_TOKEN }}
