name: Assign Runners
run-name: Assign Runners

on:
  repository_dispatch:
    types: ["assign"]
  workflow_call:

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make binary executable
        run: chmod +x ./bin/assign

      - name: Run binary
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_NAME: ${{ vars.DB_NAME }}
          QUERY_DB_NAME: ${{ vars.QUERY_DB_NAME }}
        run: ./bin/assign

  create:
    needs: assign
    runs-on: ubuntu-latest

    steps:
      - name: Say hi
        run: echo "Hello, world!"
