name: Assign Runners
run-name: Assign Runners

on:
  repository_dispatch:
    types: ["assign"]
  workflow_call:
    inputs:
      run:
        description: "Whether to run the job or not"
        required: false
        default: true
        type: boolean

jobs:
  assign:
    runs-on: ubuntu-latest
    if: ${{ inputs.run == true }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make binary executable
        run: chmod +x ./bin/assign

      - name: Run binary
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_NAME: ${{ vars.DB_NAME }}
          QUERY_DB_NAME: ${{ vars.QUERY_DB_NAME }}
        run: ./bin/assign

  create:
    needs: assign
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make binary executable
        run: chmod +x ./bin/runners

      - name: Run binary
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_NAME: ${{ vars.DB_NAME }}
          QUERY_DB_NAME: ${{ vars.QUERY_DB_NAME }}
        run: ./bin/runners

      - name: Add runners
      - run: |
         git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "add runners"
          git push
