name: runner_8
run-name: Runner 8
"on":
  repository_dispatch:
    types: [run2]
jobs:
  run_binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env: {}
      - name: Make binary executable
        run: chmod +x ./bin/profit
        env: {}
      - name: Run binary
        run: ./bin/profit --runner-id=8
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_AUTH_TOKEN: ${{ secrets.DB_AUTH_TOKEN }}
