name: runner_3
run-name: Runner 3
"on":
    repository_dispatch:
        types: [run1]
jobs:
    run_binary:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              env: {}
            - name: Make binary executable
              run: chmod +x ./bin/profit
              env: {}
            - name: Run binary
              run: ./bin/profit --update-prices --runner-id=3
              env:
                DB_NAME: ${{ vars.DB_NAME }}
                DB_URL: ${{ secrets.DB_URL }}
                QUERY_DB_NAME: ${{ vars.QUERY_DB_NAME }}
