name: runner_2
"on":
    repository_dispatch:
        types: [run]
jobs:
    run_binary:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              env: {}
            - name: Make binary executable
              run: chmod +x ./bin/update
              env: {}
            - name: Run binary
              run: ./bin/update --runner-id=0
              env:
                DB_NAME: ${{ vars.DB_NAME }}
                DB_URL: ${{ secrets.DB_URL }}
                QUERY_DB_NAME: ${{ vars.QUERY_DB_NAME }}
